/* 
© 2025 Aravinth Raj R. All rights reserved.
Unauthorized copying of this file, via any medium, is strictly prohibited.
Proprietary and confidential.  
Written by Aravinth Raj R <aravinthr235@gmail.com>, 2025.
*/
export const HOME_CONFIG = {
  greet: "Welcome Back,",
  userName: "Aravinth",
  waveSign: "👋",
  schedules: "SCHEDULES",
  noClass: "No Classes Scheduled",
  buttonTitle: "Retry",
  attendanceButton: "Mark Attd.",
  batch: "Batch : ",
  year: "Year : ",
  faculty: "Faculty : ",
  semester: "Semester : ",
  data: [
    {
      subName: "23CS53C - Database Management Systems",
      batch: "A",
      year: "III",
      faculty: "Mr. Suresh Kumar",
      semester: "V",
      date: "11-12-2025",
      startTime: "08:25 AM",
      endTime: "09:15 AM",
    },
    {
      subName: "23CS51C - Theory of Computation",
      batch: "A",
      year: "III",
      faculty: "Mr. R. Aravinth Raj",
      semester: "V",
      date: "11-12-2025",
      startTime: "09:15 AM",
      endTime: "10:05 AM",
    },
    {
      subName: "23CS52C - Computer Networks",
      batch: "A",
      year: "III",
      faculty: "Ms. Priya K",
      semester: "V",
      date: "11-12-2025",
      startTime: "10:05 AM",
      endTime: "10:55 AM",
    },
    {
      subName: "23CS54C - Operating Systems",
      batch: "A",
      year: "III",
      faculty: "Mrs. Divya R",
      semester: "V",
      date: "11-12-2025",
      startTime: "11:00 AM",
      endTime: "11:50 AM",
    },
    {
      subName: "23CS55C - Artificial Intelligence",
      batch: "A",
      year: "III",
      faculty: "Mr. R. Aravinth Raj",
      semester: "V",
      date: "11-12-2025",
      startTime: "11:50 AM",
      endTime: "12:40 PM",
    },
    {
      subName: "23CS56C - Software Engineering",
      batch: "A",
      year: "III",
      faculty: "Ms. Harini S",
      semester: "V",
      date: "11-12-2025",
      startTime: "01:30 PM",
      endTime: "02:20 PM",
    },
    {
      subName: "23CS57L - DBMS Laboratory",
      batch: "A",
      year: "III",
      faculty: "Mr. Manoj B",
      semester: "V",
      date: "11-12-2025",
      startTime: "02:20 PM",
      endTime: "03:10 PM",
    },
    {
      subName: "23CS58L - Networking Laboratory",
      batch: "A",
      year: "III",
      faculty: "Mrs. Shalini T",
      semester: "V",
      date: "11-12-2025",
      startTime: "03:10 PM",
      endTime: "11:45 PM",
    },
  ],
};
